// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Fortune.Repository.Models;

[Table("booking")]
public partial class Booking
{
    [Key]
    public Guid booking_id { get; set; }

    [Required]
    [StringLength(255)]
    public string description { get; set; }

    public bool type { get; set; }

    public Guid user_id { get; set; }

    public long status { get; set; }

    public Guid staff_id { get; set; }

    [InverseProperty("booking")]
    public virtual ICollection<Mini_game> Mini_games { get; set; } = new List<Mini_game>();

    [InverseProperty("booking")]
    public virtual ICollection<Plan> Plans { get; set; } = new List<Plan>();

    [ForeignKey("user_id")]
    [InverseProperty("Bookings")]
    public virtual User user { get; set; }
}