// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Fortune.Repository.Models;

[Table("booking")]
public partial class Booking
{
    [Key]
    public Guid booking_id { get; set; }

    [Required]
    [StringLength(255)]
    public string description { get; set; }

    public bool type { get; set; }

    public Guid user_id { get; set; }

    public long status { get; set; }

    public Guid staff_id { get; set; }

    public Guid? minigame_id { get; set; }
    public Guid? plan_id { get; set; }

    [ForeignKey(nameof(minigame_id))]
    [JsonIgnore]
    [InverseProperty("Bookings")]
    public virtual Mini_game Mini_game { get; set; }

    [ForeignKey(nameof(plan_id))]
    [JsonIgnore]
    [InverseProperty("Bookings")]
    public virtual Plan Plan { get; set; }
    [ForeignKey("user_id")]
    [InverseProperty("Bookings")]
    [JsonIgnore]
    public virtual User user { get; set; }
}