// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Fortune.Repository.Models;

[Table("Mini game")]
public partial class Mini_game
{
    [Key]
    [Column("minigame_id")]
    public Guid miniGame_id { get; set; }

    [Required]
    [StringLength(255)]
    [Column("mg_name")]
    public string MG_name { get; set; }

    [Required]
    [StringLength(255)]
    [Column("mg_des")]
    public string MG_des { get; set; }

    public byte[] picture { get; set; }

    public int count { get; set; }

    [StringLength(255)]
    [Column("filename")]
    public string FileName { get; set; }

    [StringLength(100)]
    [Column("filetype")]
    public string FileType { get; set; }
    [Column("FileUrl")]
    public string FileUrl { get; set; }
    [Column("PublicId")]
    public string PublicId { get; set; }
    [InverseProperty(nameof(Booking.Mini_game))]
    [JsonIgnore]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

}