// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Fortune.Repository.Models;

[Table("plan")]
public partial class Plan
{
    [Key]
    [Column("plan_id")]
    public Guid Plan_id { get; set; }

    [Required]
    [StringLength(255)]
    [Column("plan_name")]
    public string Plan_name { get; set; }

    [Required]
    [StringLength(255)]
    [Column("plan_des")]
    public string Plan_des { get; set; }

    public Guid booking_id { get; set; }

    public int count { get; set; }
    [Column("filedata")]
    public byte[] FileData { get; set; }

    [StringLength(255)]
    [Column("filename")]
    public string FileName { get; set; }

    [StringLength(50)]
    [Column("filetype")]
    public string FileType { get; set; }

    [ForeignKey("booking_id")]
    [InverseProperty("Plans")]
    public virtual Booking booking { get; set; }
}