// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace Fortune.Repository.Models;

[Table("plan")]
public partial class Plan
{
    [Key]
    [Column("plan_id")]
    public Guid Plan_id { get; set; }

    [Required]
    [StringLength(255)]
    [Column("plan_name")]
    public string Plan_name { get; set; }

    [Required]
    [StringLength(255)]
    [Column("plan_des")]
    public string Plan_des { get; set; }

    public int count { get; set; }

    [StringLength(255)]
    [Column("filename")]
    public string FileName { get; set; }

    [StringLength(50)]
    [Column("filetype")]
    public string FileType { get; set; }
    [Column("FileUrl")]
    public string FileUrl { get; set; }
    [Column("PublicId")]
    public string PublicId { get; set; }
    [InverseProperty(nameof(Booking.Plan))]
    [JsonIgnore]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

}