// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Fortune.Repository.Models;
[Table("staff")]
public partial class Staff
{
    [Key]
    public Guid staff_id { get; set; }

    public Guid user_id { get; set; }

    [Required]
    [StringLength(255)]
    public string address { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("Staff")]
    public virtual User user { get; set; }
}