// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Fortune.Repository.Models;

[Table("User")]
public partial class User
{
    [Key]
    public Guid user_id { get; set; }

    [Required]
    [StringLength(255)]
    [Column("username")]
    public string UserName { get; set; }

    [Required]
    [StringLength(255)]
    [Column("password")]
    public string Password { get; set; }

    [Required]
    [StringLength(255)]
    [Column("salt")]
    public string Salt { get; set; }
    [Column("phone")]
    public long? Phone { get; set; }

    [StringLength(255)]
    [Column("email")]
    public string Email { get; set; }
    [Column("role")]

    public long Role { get; set; }

    [Required]
    [StringLength(255)]
    [Column("fullname")]
    public string FullName { get; set; }
    [Column("isactive")]
    public bool IsActive { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    [InverseProperty("user")]
    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}